/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./app/**/*.{js,jsx}",
    "./src/**/*.{js,jsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#14424C",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",

      {
        aqua: {
          "color-scheme": "dark",
          primary: "#09ecf3",
          "primary-content": "#005355",
          secondary: "#966fb3",
          accent: "#ffe999",
          neutral: "#3b8ac4",
          "base-100": "#345da7",
          info: "#2563eb",
          success: "#16a34a",
          warning: "#d97706",
          error: "oklch(73.95% 0.19 27.33)",
        },
      },
      {
        sunset: {
          "color-scheme": "dark",
          primary: "#ff6b6b",
          "primary-content": "#4a1a1a",
          secondary: "#ffcc5c",
          accent: "#ffeead",
          neutral: "#6c7a89",
          "base-100": "#2c3e50",
          info: "#3498db",
          success: "#2ecc71",
          warning: "#f39c12",
          error: "#e74c3c",
        },
      },
      {
        ocean: {
          "color-scheme": "dark",
          primary: "#1abc9c",
          "primary-content": "#145b5b",
          secondary: "#2ecc71",
          accent: "#f1c40f",
          neutral: "#34495e",
          "base-100": "#2c3e50",
          info: "#3498db",
          success: "#27ae60",
          warning: "#e67e22",
          error: "#e74c3c",
        },
      },
      {
        sky: {
          "color-scheme": "light",
          primary: "#3498db",
          "primary-content": "#154360",
          secondary: "#9b59b6",
          accent: "#f1c40f",
          neutral: "#95a5a6",
          "base-100": "#ecf0f1",
          info: "#3498db",
          success: "#2ecc71",
          warning: "#e67e22",
          error: "#e74c3c",
        },
      },
      {
        fire: {
          "color-scheme": "light",
          primary: "#e74c3c",
          "primary-content": "#922b21",
          secondary: "#f39c12",
          accent: "#f1c40f",
          neutral: "#bdc3c7",
          "base-100": "#ecf0f1",
          info: "#3498db",
          success: "#2ecc71",
          warning: "#e67e22",
          error: "#e74c3c",
        },
      },
      {
        royal: {
          "color-scheme": "dark",
          primary: "#8e44ad",
          "primary-content": "#4a235a",
          secondary: "#2980b9",
          accent: "#f1c40f",
          neutral: "#34495e",
          "base-100": "#2c3e50",
          info: "#3498db",
          success: "#27ae60",
          warning: "#e67e22",
          error: "#e74c3c",
        },
      },
      {
        mint: {
          "color-scheme": "light",
          primary: "#1abc9c",
          "primary-content": "#0b5345",
          secondary: "#2ecc71",
          accent: "#f1c40f",
          neutral: "#95a5a6",
          "base-100": "#ecf0f1",
          info: "#3498db",
          success: "#2ecc71",
          warning: "#e67e22",
          error: "#e74c3c",
        },
      },
      {
        cherry: {
          "color-scheme": "dark",
          primary: "#e74c3c",
          "primary-content": "#5e0c0c",
          secondary: "#c0392b",
          accent: "#f39c12",
          neutral: "#34495e",
          "base-100": "#2c3e50",
          info: "#3498db",
          success: "#2ecc71",
          warning: "#e67e22",
          error: "#e74c3c",
        },
      },
      {
        leaf: {
          "color-scheme": "light",
          primary: "#2ecc71",
          "primary-content": "#145a32",
          secondary: "#27ae60",
          accent: "#f1c40f",
          neutral: "#95a5a6",
          "base-100": "#ecf0f1",
          info: "#3498db",
          success: "#2ecc71",
          warning: "#e67e22",
          error: "#e74c3c",
        },
      },
      {
        gold: {
          "color-scheme": "dark",
          primary: "#f39c12",
          "primary-content": "#7e5109",
          secondary: "#e67e22",
          accent: "#f1c40f",
          neutral: "#34495e",
          "base-100": "#2c3e50",
          info: "#3498db",
          success: "#27ae60",
          warning: "#e67e22",
          error: "#e74c3c",
        },
      },
      {
        azure: {
          "color-scheme": "light",
          primary: "#3498db",
          "primary-content": "#154360",
          secondary: "#2980b9",
          accent: "#f1c40f",
          neutral: "#95a5a6",
          "base-100": "#ecf0f1",
          info: "#3498db",
          success: "#2ecc71",
          warning: "#e67e22",
          error: "#e74c3c",
        },
      },
      {
        oceanic: {
          "color-scheme": "dark",
          primary: "#0077b6",
          "primary-content": "#e1f5fe",
          secondary: "#00b4d8",
          accent: "#caf0f8",
          neutral: "#023e8a",
          "base-100": "#03045e",
          info: "#48cae4",
          success: "#90e0ef",
          warning: "#ffb703",
          error: "#fb8500",
        },
      },

      {
        sunsetblaze: {
          "color-scheme": "dark",
          primary: "#ff4e00",
          "primary-content": "#ffe5d9",
          secondary: "#ffb703",
          accent: "#fb8500",
          neutral: "#5a1e02",
          "base-100": "#3a0ca3",
          info: "#0077b6",
          success: "#00b4d8",
          warning: "#e63946",
          error: "#d00000",
        },
      },
      {
        forestwhisper: {
          "color-scheme": "light",
          primary: "#2d6a4f",
          "primary-content": "#d8f3dc",
          secondary: "#40916c",
          accent: "#f4a261",
          neutral: "#1b4332",
          "base-100": "#f1faee",
          info: "#219ebc",
          success: "#8ecae6",
          warning: "#ffba08",
          error: "#e63946",
        },
      },
      {
        tropicalvibes: {
          "color-scheme": "light",
          primary: "#f4a261",
          "primary-content": "#fff5eb",
          secondary: "#e76f51",
          accent: "#2a9d8f",
          neutral: "#264653",
          "base-100": "#e9c46a",
          info: "#2a9d8f",
          success: "#48cae4",
          warning: "#ffb703",
          error: "#d00000",
        },
      },
      {
        mysticalnight: {
          "color-scheme": "dark",
          primary: "#3a0ca3",
          "primary-content": "#e5e5e5",
          secondary: "#4cc9f0",
          accent: "#7209b7",
          neutral: "#560bad",
          "base-100": "#240046",
          info: "#9d4edd",
          success: "#f72585",
          warning: "#b5179e",
          error: "#7209b7",
        },
      },
      {
        citrusburst: {
          "color-scheme": "light",
          primary: "#ffba08",
          "primary-content": "#fff1e6",
          secondary: "#faa307",
          accent: "#f48c06",
          neutral: "#5f0f40",
          "base-100": "#eae2b7",
          info: "#9d4edd",
          success: "#f72585",
          warning: "#b5179e",
          error: "#7209b7",
        },
      },
      {
        lavenderdream: {
          "color-scheme": "light",
          primary: "#9d4edd",
          "primary-content": "#f3d5f0",
          secondary: "#c77dff",
          accent: "#e0aaff",
          neutral: "#3c096c",
          "base-100": "#f4e1ff",
          info: "#ff66b3",
          success: "#f72585",
          warning: "#ffba08",
          error: "#d00000",
        },
      },
      {
        emeraldglow: {
          "color-scheme": "light",
          primary: "#2a9d8f",
          "primary-content": "#e0f7fa",
          secondary: "#264653",
          accent: "#6c757d",
          neutral: "#1d3557",
          "base-100": "#f1faee",
          info: "#457b9d",
          success: "#48cae4",
          warning: "#ffba08",
          error: "#d00000",
        },
      },
      {
        peachblossom: {
          "color-scheme": "light",
          primary: "#ff6b6b",
          "primary-content": "#fff1e6",
          secondary: "#ffa69e",
          accent: "#ff8c94",
          neutral: "#f7a1a1",
          "base-100": "#ffffff",
          info: "#ffcad4",
          success: "#48cae4",
          warning: "#ffba08",
          error: "#d00000",
        },
      },
      {
        cosmicflare: {
          "color-scheme": "dark",
          primary: "#7209b7",
          "primary-content": "#f3d5f0",
          secondary: "#3a0ca3",
          accent: "#f72585",
          neutral: "#240046",
          "base-100": "#2d00f7",
          info: "#4cc9f0",
          success: "#3a86ff",
          warning: "#f77f00",
          error: "#d00000",
        },
      },
    ],
  },
  plugins: [require("tailwindcss-animate"), require("daisyui")],
};
