export default [
  {
    id: 1,
    name: "default",
    img: "/default.png",
    value: "none",
    key: "1px",
  },
  {
    id: 2,
    name: "retro",
    img: "/retro.png",
    value: "5px 5px 0px black",
    key: "boxshadow",
  },
  {
    id: 3,
    name: "solid",
    img: "/solid.png",
    value: "2px solid #000",
    key: "solid",
  },
  {
    id: 4,
    name: "dashed",
    img: "/dashed.png",
    value: "2px dashed #000",
    key: "dashed",
  },
  {
    id: 5,
    name: "double",
    img: "/double.png",
    value: "4px double #000",
    key: "4px",
  },
  {
    id: 6,
    name: "groove",
    img: "/groove.png",
    value: "3px groove #000",
    key: "3px",
  },
  {
    id: 7,
    name: "ridge",
    img: "/ridge.png",
    value: "3px ridge #000",
    key: "3px",
  },
  {
    id: 8,
    name: "inset",
    img: "/inset.png",
    value: "3px inset #000",
    key: "3px",
  },
  {
    id: 9,
    name: "outset",
    img: "/outset.png",
    value: "3px outset #000",
    key: "3px",
  },
  {
    id: 10,
    name: "dotted",
    img: "/dotted.png",
    value: "2px dotted #000",
    key: "2px",
  },

  {
    id: 12,
    name: "shadow",
    img: "/shadow.png",
    value: "0 0 10px rgba(0, 0, 0, 0.5)",
    key: "boxshadow",
  },
  {
    id: 1,
    name: "subtle",
    img: "/subtle.png",
    value: "0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)",
    key: "boxshadow",
  },

  {
    id: 4,
    name: "neon",
    img: "/neon.png",
    value: "0 0 10px #00ff00, 0 0 20px #00ff00, 0 0 30px #00ff00",
    key: "boxshadow",
  },
  {
    id: 5,
    name: "glow",
    img: "/glow.png",
    value: "0 0 8px rgba(31, 110, 255, 0.6)",
    key: "boxshadow",
  },
  {
    id: 6,
    name: "dbl-border",
    img: "/double-border.png",
    value: "3px double #000",
    key: "border",
  },
  {
    id: 7,
    name: "dashed",
    img: "/dashed.png",
    value: "2px dashed #000",
    key: "border",
  },
  {
    id: 8,
    name: "inset",
    img: "/inset.png",
    value: "inset 0 2px 4px rgba(0, 0, 0, 0.1)",
    key: "boxshadow",
  },
  {
    id: 9,
    name: "blur",
    img: "/blur.png",
    value: "0 0 15px rgba(0, 0, 0, 0.2)",
    key: "boxshadow",
  },
  {
    id: 10,
    name: "groove",
    img: "/groove.png",
    value: "4px groove #000",
    key: "border",
  },
];
